Add implementation dg
AY2122S1-CS2103T-T11-3/tp pull request #144
Opened 2021-10-27 12:34 UTC by ChuangZheQuan

<img width="512" alt="Screenshot 2021-10-31 at 5 31 35 PM" src="https://user-images.githubusercontent.com/59484281/139576276-fc18b1e7-70c2-47a5-b741-d3eb1892a1e1.png">

Delete Appointment Activity Diagram

<img width="1022" alt="Screenshot 2021-10-31 at 6 38 47 PM" src="https://user-images.githubusercontent.com/59484281/139578668-5ebe91f8-cdc2-44e8-9e19-1e1b979f7fab.png">

Delete Appointment Sequence Diagram

<img width="1226" alt="Screenshot 2021-10-31 at 5 34 54 PM" src="https://user-images.githubusercontent.com/59484281/139576374-3dedb30b-3af6-481c-9e91-a0080c1b05c4.png">

Add Appointment Activity Diagram

<img width="1019" alt="Screenshot 2021-10-31 at 6 39 07 PM" src="https://user-images.githubusercontent.com/59484281/139578679-f3eefcf5-a4ae-4a36-b5b3-aba63dd7bf8d.png">

Add Appointment Sequence Diagram

2021-10-30 14:28 UTC, pualixue commented on docs/UserGuide.md
> +* Duration has to be an integer between 0 and 120 (minutes).
The current implementation is 1-120 minutes.

2021-10-30 17:53 UTC, pualixue requested changes
Nice detailed test cases for the manual testing section. Some suggestions to be considered.
For the activity diagrams, I think the if-else conditions need to be in square brackets and an empty diamond.

2021-10-30 17:53 UTC, pualixue commented on docs/DeveloperGuide.md
> +####Implementation
Maybe add a space after `####` to avoid formatting issues.

2021-10-30 17:53 UTC, pualixue commented on docs/DeveloperGuide.md
> +2. `DeleteAppointmentCommandParser` will check if the index is valid. If the index is valid, a new `DeleteAppointmentCommand` which extends
`DeleteAppointmentCommand` which extends `AppointmentCommand` <- missing

2021-10-30 17:53 UTC, pualixue commented on docs/DeveloperGuide.md
> +      Expected: An appointment is added. Details of the appointment shown in the response box. The appointment does not show up in the appointment list.
Might need to change since we will be showing the added appointment now.

2021-10-30 17:53 UTC, pualixue commented on docs/DeveloperGuide.md
> +    1. Prerequisites: list all appointments using the `appt -l` command. There must be multiple doctors and patients in the patient and doctor lists. There are less than 100 patients and doctors.
Perhaps using `appt -f` as they might not have appointments for the current day?

2021-10-30 17:53 UTC, pualixue commented on docs/DeveloperGuide.md
> +    1. Prerequisites: list all appointments using the `appt -l` command. Multiple appointments in the list.
Perhaps using `appt -f` as they might not have appointments for the current day?

2021-10-31 09:47 UTC, pualixue commented on docs/diagrams/AddAppointmentActivityDiagram.puml
> +         else ([else]])
```suggestion
         else ([else])
```

2021-10-31 14:59 UTC, pualixue approved these changes
LGTM

2021-10-31 20:05 UTC, jiayi1129 approved these changes
LGTM! 👍

2021-11-01 12:40 UTC, merged