Edit target user profile, value proposition, user stories, use cases and contributions
AY2122S1-CS2103T-T11-3/tp pull request #15
Opened 2021-09-22 04:11 UTC by ChuangZheQuan

2021-09-23 09:42 UTC, pualixue requested changes
All good except some minor typo issues.

2021-09-23 09:42 UTC, pualixue commented on docs/DeveloperGuide.md
> +| `* *`    | clinic receptionist with many patients to manage| sort doctors by risk      | locate a doctor easily                                                |
I think doctors won't have risk profiles, maybe can remove this user story?

2021-09-23 09:42 UTC, pualixue commented on docs/DeveloperGuide.md
> +| `*`      | clinic receptionist                        | hide private contact details   | minimize chance of someone else seeing them by accident                |
This line is a duplicate of the one above.

2021-09-23 09:42 UTC, pualixue commented on docs/DeveloperGuide.md
> +3.  User requests to add a risk profile a specific person in the list
Perhaps adding a "to" after "add a risk profile"?

2021-09-23 09:42 UTC, pualixue commented on docs/DeveloperGuide.md
> +4.  PlannerMD edits the patient's personal details is be reflected immediately
Perhaps changing "is be" to "which is"?

2021-09-23 09:42 UTC, pualixue commented on docs/AboutUs.md
> +* Responsibilities: Responsible for the quality of various project documents.
Maybe this file can be removed since it is already in another pull request.

2021-09-23 09:50 UTC, hpkoh requested changes
I have left some comments on some references related to AB3 to be refactored for PlannerMD and suggestions for the user guide content.

2021-09-23 09:50 UTC, hpkoh commented on docs/DeveloperGuide.md
> +| `* *`    | clinic receptionist | edit patients by risk     | change any additional information about the patient                                             |
Abit confused by this user story

2021-09-23 09:50 UTC, hpkoh commented on docs/DeveloperGuide.md
> +| `*`      | clinic receptionist                        | hide private contact details   | minimize chance of someone else seeing them by accident                |
Same as line 301

2021-09-23 09:50 UTC, hpkoh commented on docs/DeveloperGuide.md
> +(For all use cases below, the **System** is `PlannerMD` and the **Actor** is the `user`, unless specified otherwise)
Maybe user, in this case, can be receptionist?

2021-09-23 09:50 UTC, hpkoh commented on docs/DeveloperGuide.md
> +4.  PlannerMD deletes the person which is reflected immediately in the list
For consistency, maybe we can standardize our persons to patients

2021-09-23 09:50 UTC, hpkoh commented on docs/DeveloperGuide.md
> +
For use cases, I think we should mark those which are not implemented as coming soon. 
Also, for many of the uses cases, since `find` is part of the steps, maybe we should include and reference that use case since many of the extensions are actually due to that feature

2021-09-23 09:50 UTC, hpkoh commented on docs/team/chuangzhequan.md
> +AddressBook - Level 3 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is writ
References to Addressbook to be changed to PlannerMD.

2021-09-23 12:24 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +| `* *`    | clinic receptionist with many patients to manage| sort doctors by risk      | locate a doctor easily                                                |
okie

2021-09-23 12:28 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +| `* *`    | clinic receptionist | edit patients by risk     | change any additional information about the patient                                             |
yep typo

2021-09-23 12:30 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +(For all use cases below, the **System** is `PlannerMD` and the **Actor** is the `user`, unless specified otherwise)
I feel like the word is too long and to reuse it throughout the use cases may be tiresome for the reader

2021-09-23 12:30 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +4.  PlannerMD deletes the person which is reflected immediately in the list
I'll put patients and doctors

2021-09-23 12:37 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +
hmm i see your point but the cs2103 website says this: 
```Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first```

that was why i didn't include it

2021-09-23 13:36 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +(For all use cases below, the **System** is `PlannerMD` and the **Actor** is the `user`, unless specified otherwise)
nvm ure right

2021-09-23 18:13 UTC, hpkoh commented on docs/DeveloperGuide.md
> +
Ah, I think after we implement our other features we will have sufficiently complex use cases, just seems repetitive for now. Let's discuss this with the team in our next meeting.

2021-09-23 18:19 UTC, hpkoh approved these changes
LGTM 👍

2021-09-24 15:13 UTC, pualixue approved these changes

2021-09-25 03:24 UTC, merged