Update DG manual testing
AY2122S1-CS2103T-T11-3/tp pull request #233
Opened 2021-11-04 05:52 UTC by pualixue

2021-11-04 13:56 UTC, Haozeee requested changes

2021-11-04 13:56 UTC, Haozeee commented on docs/DeveloperGuide.md
> +       Expected: All existing patients are listed.
Is 2 and 3 the same?

2021-11-04 13:56 UTC, Haozeee commented on docs/DeveloperGuide.md
> +    9. Test case: `edit 1 t/experienced`<br>
Perhaps can add an `edit 1 t/` test case to show that this deletes all existing tags.

2021-11-04 14:33 UTC, pualixue commented on docs/DeveloperGuide.md
> +       Expected: All existing patients are listed.
Oops good catch, supposed to be different

2021-11-05 06:33 UTC, Haozeee approved these changes

2021-11-05 07:40 UTC, merged