Update Doctor use cases and standardize format
AY2122S1-CS2103T-T11-3/tp pull request #250
Opened 2021-11-06 11:16 UTC by hpkoh

2021-11-06 14:42 UTC, Haozeee requested changes

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +**Use case: UC03P Finding doctors** <br>
This should be UC03D right

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +Same as UC02P but references to patient is replaced with doctor instead.
This should be UC03P

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +  Use case ends.
I think this use case ends is not necessary since it is already stated in line 595 that the use case resumes at a certain step

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +      Use case resumes at step 1.
Should this be step 2?

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
>      * 3a1. PlannerMD shows an error message.
Should be 2a1

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +    * 3b1. PlannerMD shows an error message.
Should be 2b1

2021-11-06 14:42 UTC, Haozeee commented on docs/DeveloperGuide.md
> +**Precondition:** PlannerMD is displaying the patient tab.
I really don't think we should have any references to `patient tab` in our use case as it's a UI detail.

This is from the textbook (refer to point 2)
![Screenshot 2021-11-06 at 22 33 55](https://user-images.githubusercontent.com/65447873/140613543-731b9829-2a06-4400-a612-129ca39ca750.png)

2021-11-06 18:18 UTC, hpkoh commented on docs/DeveloperGuide.md
> +      Use case resumes at step 1.
Im actually not sure which step it should be.  I didn't change the rest bc I was wondering if it should be 1 or 2. From AB3 it seems that we should start from the prev step.

2021-11-06 18:18 UTC, hpkoh commented on docs/DeveloperGuide.md
> +**Precondition:** PlannerMD is displaying the patient tab.
Yeah youre right. Display patient records then?

2021-11-07 06:03 UTC, Haozeee commented on docs/DeveloperGuide.md
> +**Precondition:** PlannerMD is displaying the patient tab.
I think in this case should just leave the preconditions empty. Since use cases are specified before the feature is implemented, thus it shouldn't have any implementation details. Displaying patient records is sort of an implementation detail, you would only know about it after implementing the feature. It is possible to implement the feature in another way without having this precondition. 
For use cases, the preconditions should be something like `the patient list is not empty` or `the patient added is not currently in the patient list`.

2021-11-07 09:14 UTC, Haozeee approved these changes

2021-11-07 09:14 UTC, merged