Add Patient and Risk field
AY2122S1-CS2103T-T11-3/tp pull request #39
Opened 2021-09-28 16:26 UTC by jiayi1129

- Add `Patient` and `Risk` Classes
- Add `PatientTest` and `RiskTest` to tests
- Add `PatientBuilder` and `TypicalPatients` to `testutils`

2021-09-30 11:20 UTC, Haozeee reviewed
Overall, I think the code looks good with some minor changes needed here and there. Since there are a lot of changes, there may be some things that I missed out on. I'll try to take a look again when I have time.

While the code works for now, the OOP design of it can be improved. Since, we will be adding doctors in the future and patients and doctors will share a lot of similar fields and functionalities, we can abstract out some of the common parts in the OOP design. For example, we can have a abstract AddPersonCommand and then an abstract AddPatientCommand extending from it. The functionality related to the data fields in Person can be implemented in AddPersonCommand while the extra patient fields (Risk) can be added in the AddPatientCommand. This will allow us to have less repeated code when we add Doctors, and make the codebase easier to maintain as well.

2021-09-30 14:06 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/model/patient/Patient.java
> +        Patient otherPerson = (Patient) other;
Good catch! Will change thanks 👍

2021-09-30 14:07 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/model/patient/Patient.java
> +                && otherPerson.getRisk().equals(getRisk());
Yes that's a good suggestion, I will make the changes as well.

2021-09-30 14:10 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/parser/ParserUtil.java
> +        String trimmedRisk = risk.trim();
Sure, that sounds like a good to have and an easy addition

2021-09-30 14:11 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/storage/JsonAdaptedPatient.java
> + * Jackson-friendly version of {@link Person}.
Good catch!

2021-09-30 16:25 UTC, jiayi1129 commented
Noting some discussions that I had with @Haozeee 

**Commands**
Perhaps it is possible to have a more general method named `AddPersonCommand` that inherits from `AddCommand`, then `AddPatientCommand` and `AddDoctorCommand` can inherit from the `AddPersonCommand`.

**Parsers**
Similar to _Commands_, perhaps it is possible to add a `AddPersonCommandParser` to bridge `AddDoctorCommandParser` / `AddPatientCommandParser` and `AddCommand` to simplify some common functions.

**UniquePersonList**
Perhaps it is possible to use this for both the unique patient and doctor list. However some methods like `public void setPersons(List<Person> persons)` and `public ObservableList<Person> asUnmodifiableObservableList()` may prove to be difficult to modify based on the invariant property of generics. I do believe changing the class to 
`public class UniquePersonList<T extends Person> implements Iterable<Person>` and then modifying the function's parameters would be a good way to move forward but there could be some dangerous casts. Hence this should be a standalone issue and be resolved in a separate PR. A synonymous `UniquePatientList` is used as interim.

2021-09-30 16:54 UTC, jiayi1129 reviewed
@Haozeee I have done the UI for risk as I did its implementation. I adapted the design from your PR.

2021-09-30 16:57 UTC, jiayi1129 commented
![image](https://user-images.githubusercontent.com/35002411/135498651-b85edb1a-5558-4cf9-b4cb-f2b9a2861be9.png)
Current look for `Risk` tag UI

2021-09-30 18:46 UTC, pualixue requested changes
LGTM overall. There are a few cosmetic issues that I noticed.

2021-09-30 18:46 UTC, pualixue commented on src/test/java/seedu/plannermd/model/patient/RiskTest.java
> +    }
Are the *addresses* supposed to be *risk*?

2021-09-30 18:46 UTC, pualixue commented on src/test/java/seedu/plannermd/storage/JsonAdaptedPatientTest.java
> +    public void toModelType_validpatientDetails_returnspatient() throws Exception {
Minor typo.
```suggestion
    public void toModelType_validPatientDetails_returnsPatient() throws Exception {
```

2021-09-30 18:46 UTC, pualixue commented on src/test/java/seedu/plannermd/testutil/PlannerMdBuilder.java
>       * Adds a new {@code Person} to the {@code PlannerMd} that we are building.
Perhaps this should be Patient?
```suggestion
     * Adds a new {@code Patient} to the {@code PlannerMd} that we are building.
```

2021-10-01 01:49 UTC, ChuangZheQuan requested changes
Overall looks good, I'm thinking maybe Person should be an abstract class, but we can discuss that in the future. Just some minor changes needed and logic looks fine. Good job!

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/logic/commands/EditPatientCommandTest.java
> +    public void execute_duplicatePersonUnfilteredList_failure() {
maybe can change the method name to `execute_deuplicatePatientUnfilteredList_failure`?

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/logic/commands/EditPatientCommandTest.java
> +    public void execute_duplicatePersonFilteredList_failure() {
same here!

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/logic/commands/EditPatientCommandTest.java
> +    public void execute_invalidPersonIndexFilteredList_failure() {
here too!

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/logic/commands/FindPatientCommandTest.java
>      public void execute_zeroKeywords_noPersonFound() {
maybe change to patient? unless can just keep it as `FindCommandTest.java` and add doctors here in the future too!

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/model/patient/PatientTest.java
> +        assertTrue(ALICE.equals(aliceCopy));
I'm thinking the the future we may need to differentiate the names between patients and doctors, maybe like adding the DR prefix in front of the name `DR_ALICE` for e.g., to make it clearer, wdyt?

2021-10-01 01:49 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/model/person/UniquePatientListTest.java
> +package seedu.plannermd.model.person;
maybe change the`person` in the test method names to `patient`?

2021-10-01 18:58 UTC, jiayi1129 commented on docs/tutorials/TracingCode.md
> +       Person editedPerson = createEditedPerson(personToEdit, editPatientDescriptor);
I think we need to update the whole md file together next time. So I just revert this back to `editPersonDescriptor` for now.

2021-10-02 03:08 UTC, pualixue approved these changes
Great job! Do consider my comment below.

2021-10-02 03:08 UTC, pualixue commented on src/test/java/seedu/plannermd/model/patient/RiskTest.java
>          assertTrue(Risk.isValidRisk("LOW")); // long address
Perhaps can remove the comments too as they are not related to risk.
```suggestion
        assertTrue(Risk.isValidRisk("MEDIUM"));
        assertTrue(Risk.isValidRisk("LOW"));
```

2021-10-02 12:12 UTC, hpkoh requested changes
Good job on refractoring the codebase to extend to other identity for `Person`

I added some comments on approaches and philosophy we could adopt for the extension.

I have also added design philosophies zhequan, you and haoze have brought up to discuss as part of our agenda for our upcoming meeting.

2021-10-02 12:12 UTC, hpkoh commented on src/main/java/seedu/plannermd/logic/commands/editcommand/EditPatientCommand.java
>      }
For our edit command to be extensible to other type of Persons, I think we could use a factory method within `EditCommand` which handles the query for the Person at `INDEX` and returns the corresponding edit command. However, there will be concerns for identity specific tokens that users may try to use with other identities.

2021-10-03 08:11 UTC, merged