Allow adding individual tags
AY2122S1-CS2103T-T11-3/tp pull request #40
Opened 2021-09-29 14:49 UTC by pualixue

2021-09-30 14:51 UTC, ChuangZheQuan requested changes
Nice! Your code looks good! I like the way you implemented your stuff. Just some minor corrections needed. However, I think you can write some tests for the Flag class? Just to check whether it works right. That should be quite simple since it doesn't have many features! Good job!

2021-09-30 14:51 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/logic/commands/DeleteTagCommand.java
> +    @Override
I think you need to add javadocs for public method

2021-09-30 14:51 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/logic/commands/TagCommand.java
> +        List<Person> lastShownList = model.getFilteredPersonList();
Same here! I think need javadocs

2021-09-30 14:51 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/logic/commands/DeleteTagCommand.java
> +    }
LGTM

2021-09-30 14:51 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/logic/parser/Flag.java
> +        this.flag = flag;
Maybe can do a `requireNonNull` check? Like this, in your `hashCode` you don't need to check if its null too! Also, it can remain kinda consistent with the other classes

2021-09-30 15:42 UTC, pualixue commented on src/main/java/seedu/plannermd/logic/parser/Flag.java
> +        this.flag = flag;
Good suggestion!

2021-10-02 00:57 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/logic/commands/DeleteTagCommand.java
> +    @Override
scrap this

2021-10-02 00:59 UTC, ChuangZheQuan reviewed
LGTM

2021-10-02 10:56 UTC, hpkoh requested changes
Code looks good!

I left a comment about the design philosophy for flag we should discuss!

2021-10-02 10:56 UTC, hpkoh commented on src/main/java/seedu/plannermd/logic/commands/DeleteTagCommand.java
> +            + PREFIX_TAG + "healthy";
Since we are using the relative index to select the desired person, would be it better to keep the formatting similar to find/edit? `tag INDEX t/

I understand in our 1.1 we suggested the id, I personally think since we are standardising using the relative index, the id field could be a bit confusing.

May I suggest that we tokenize the delete flag? `TagCommandParser :: parse` could check if the multimap contains a specific flag and return the corresponding command? I think this design would be more extensible should there be other/multiple flags.

What do you think?

2021-10-05 13:32 UTC, hpkoh approved these changes
LGTM 👍

2021-10-05 14:15 UTC, ChuangZheQuan reviewed
Just one phrasing error. Otherwise LGTM!

2021-10-05 14:15 UTC, ChuangZheQuan commented on docs/DeveloperGuide.md
> +* 3b. The given tag is non-existing.
I think the phrasing can change from `The given tag is non-existing` to the `The given tag is non-existent`

2021-10-05 18:55 UTC, merged