Add Remark feature
AY2122S1-CS2103T-T11-3/tp pull request #41
Opened 2021-09-29 16:20 UTC by hpkoh

Add `remark` field to Person
Add `Remark` command

2021-10-01 00:40 UTC, ChuangZheQuan reviewed
LGTM!

2021-10-01 19:46 UTC, jiayi1129 requested changes
Overall it looks great, but do refer to the comments below.

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/commands/EditCommand.java
> +
Perhaps can remove this blank line for consistency!

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/commands/EditCommand.java
> +
Perhaps can remove these blank lines for consistency

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/parser/ParserUtil.java
> +
Perhaps can remove these blank lines for consistency

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_REMARK = new Prefix("r/");
Is this necessary? I remember we are only adding remarks via the `remark` command and it should not use the `add` command at all. Also, this would conflict with risk as risk uses `r/` as the prefix as well.

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/logic/parser/AddCommandParser.java
> +        Remark remark = new Remark("");
Perhaps you can consider using a factory method in Remark class to get an empty remark. So perhaps something like
```
Remark remark = Remark.getEmptyRemark();
```
This takes away the need to declare magic literals "" in the code base.

2021-10-01 19:46 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/model/util/SampleDataUtil.java
> +    private static final Remark EMPTY_REMARK = new Remark("");
Perhaps you can follow the format that they have used and have some with empty remarks, and others with non-empty remarks.

2021-10-01 19:46 UTC, jiayi1129 commented on src/test/java/seedu/plannermd/testutil/TypicalPersons.java
> +            .withPhone("98765432").withRemark("hehe")
remarks can be perhaps something more formal as opposed to "hehe"

2021-10-01 19:46 UTC, jiayi1129 commented on src/test/java/seedu/plannermd/logic/commands/RemarkCommandTest.java
> +    private static final String SAMPLE_REMARK = "xd";
Perhaps the sample remark can be something more formal as compared to "xd" as well

2021-10-02 12:19 UTC, hpkoh commented on src/main/java/seedu/plannermd/logic/parser/CliSyntax.java
> +    public static final Prefix PREFIX_REMARK = new Prefix("r/");
/r tokenizes the actual remark message in the remark command `Remark INDEX r/MESSAGE`. Did you manage to implement it some other way?

2021-10-02 12:20 UTC, hpkoh commented on src/main/java/seedu/plannermd/logic/parser/AddCommandParser.java
> +        Remark remark = new Remark("");
Good idea

2021-10-05 15:11 UTC, jiayi1129 requested changes
Read below

2021-10-05 15:11 UTC, jiayi1129 commented on LICENSE
> -SOFTWARE.
This should not be removed right? Do correct me if I'm wrong

2021-10-05 15:18 UTC, hpkoh commented on LICENSE
> -SOFTWARE.
Youre right i mistook this for a license in the binaries

2021-10-05 16:25 UTC, jiayi1129 approved these changes
LGTM!

2021-10-05 17:11 UTC, merged