Update PlannerMD to support Doctor and state
AY2122S1-CS2103T-T11-3/tp pull request #58
Opened 2021-10-06 17:57 UTC by hpkoh

Update plannerMD to be stateful according to the list currently displayed and interacted with.

Update planennrMD and Model to support records of Doctor and statefulness

Update UniquePersonList to be generic to support subclasses of Person

Add `ToggleCommand` to toggle between state and displayed list

2021-10-06 18:07 UTC, hpkoh commented on src/test/java/seedu/plannermd/logic/commands/ToggleCommandTest.java
> +        assertCommandSuccess(new ToggleCommand(), model, expectedCommandResult, expectedModel);
@Haozeee This test fails as now ModelManager requires a live UI component for toggling of the UI display. This functionality is implemented in `ModelManager::toggleState`. The function could be decoupled to use another function to interact with the UI. However, this requires the model interface to explicitly declare a method that's solely to handle the UI which seems inappropriate.

I think we should discuss this further with our team

2021-10-07 00:47 UTC, ChuangZheQuan reviewed
State management looks good! Just added some comments, do take a look!

2021-10-07 00:47 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/model/ModelManager.java
> +    public void updateFilteredDoctorList(Predicate<Person> predicate) {
Maybe change `Person` to Doctor?

2021-10-07 00:47 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/model/ModelManager.java
> +    }
I feel like this and `toggleState` can be combined since they serve similar purpose? correct me if i'm wrong

2021-10-07 00:47 UTC, ChuangZheQuan commented on src/test/java/seedu/plannermd/model/person/UniquePersonListTest.java
> +    private final UniquePersonList<Person> uniquePersonList = new UniquePersonList();
Should be ` private final UniquePersonList<Person> uniquePersonList = new UniquePersonList<>();` to prevent raw type?

2021-10-07 02:14 UTC, Haozeee commented on src/test/java/seedu/plannermd/logic/commands/ToggleCommandTest.java
> +        assertCommandSuccess(new ToggleCommand(), model, expectedCommandResult, expectedModel);
You can try to use the `PersonTabSwitcherStub` in ModelManagerTest.java as a placeholder for the UI during the test. Since you don't have any UI during the test, you can create an instance of `PersonTabSwitcherStub` and set the PersonTabSwitcher of `model` and `expectedModel` to be that stub. You can then refer to the boolean value in `PersonTabSwitcherStub` as a representation of the current UI view during the test. This way, you can test the logic of your code without having any UI components.

The code of `PersonTabSwitcherStub` is copied here. You need to change the access modifier and add an equals method.
```java
private static class PersonTabSwitcherStub implements PersonTabSwitcher {

        protected boolean isPatientTab = true;

        @Override
        public void switchToPatientTab() {
            isPatientTab = true;
        }

        @Override
        public void switchToDoctorTab() {
            isPatientTab = false;
        }
    }
```

The test can look something like that
```jav
        Model model = new ModelManager();
        Model expectedModel = new ModelManager();
        PersonTabSwitcher stub = new PersonTabSwitcherStub();
        PersonTabSwitcher expectedStub = new PersonTabSwitcherStub();
        expectedStub.switchToDoctorTab();

        model.setPersonTabSwitcher(stub);
        expectedModel.setPersonTabSwitcher(expectedStub);
        assertCommandSuccess(new ToggleCommand(), model, expectedCommandResult, expectedModel);
```

2021-10-07 03:37 UTC, hpkoh commented on src/main/java/seedu/plannermd/model/ModelManager.java
> +    public void updateFilteredDoctorList(Predicate<Person> predicate) {
Yeah i think the method should be changed to be specific to the subclass of Person. During my initial implementation, I was thinking that since now it is only filtered by name, a predicate<Person> would suffice.

2021-10-07 03:59 UTC, hpkoh commented on src/main/java/seedu/plannermd/model/person/UniquePersonList.java
> +                        && internalList.equals(((UniquePersonList<?>) other).internalList));
For casting, I believe <T>, <?> and raw type is essentially the same, Java just throws unchecked error if its generic or raw type.

2021-10-07 04:25 UTC, Haozeee commented on src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
> +            return new ToggleCommand();
PlannerMdParser

2021-10-07 05:51 UTC, Haozeee commented on src/test/java/seedu/plannermd/logic/commands/ToggleCommandTest.java
> +        assertCommandSuccess(new ToggleCommand(), model, expectedCommandResult, expectedModel);
That's definitely a way to do it as well. If you want to change it, its fine ah.

2021-10-07 06:45 UTC, pualixue requested changes
Looks good overall! I left some comments for Checkstyle issues.

Regarding `Person` being abstract, I think it's fine as long as we make the other relevant testutil classes extend from `Person`'s testutil classes (eg. `PatientBuilder extends PersonBuilder`, `PatientUtil extends PersonUtil`, etc). I believe we would then test `Patient` and `Doctor` separately.

2021-10-07 06:45 UTC, pualixue commented on src/test/java/seedu/plannermd/logic/commands/ToggleCommandTest.java
> +}
No newline here.

2021-10-07 06:45 UTC, pualixue commented on src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
> +import seedu.plannermd.logic.commands.*;
This `import .*` would fail the Checkstyle.

2021-10-07 06:45 UTC, pualixue commented on src/main/java/seedu/plannermd/logic/parser/PlannerMdParser.java
> +            return new ToggleCommand();
I think it's a good idea to use `Logic::getState` and pass it as argument to `parseCommand`, then we'll only need to store the state in one class.

2021-10-07 14:14 UTC, Haozeee commented on src/test/java/seedu/plannermd/logic/commands/CommandResultTest.java
> +        assertFalse(commandResult.equals(new CommandResult("feedback", false, false, true)));
Since there are test cases for another CommandResult with a different showHelp and exit value, I think would be good to also add one with a different isToggle value for consistency.

2021-10-07 18:00 UTC, merged