Add remarks and tags for doctors
AY2122S1-CS2103T-T11-3/tp pull request #65
Opened 2021-10-08 16:53 UTC by Haozeee

2021-10-09 20:11 UTC, jiayi1129 commented on src/main/java/seedu/plannermd/commons/core/Messages.java
> +    public static final String MESSAGE_INVALID_PATIENT_DISPLAYED_INDEX = "The index provided is invalid";
If we are taking away the patient term, perhaps we should rename the variable name to `MESSAGE_INVALID_DISPLAYED_INDEX` instead? What do you think?

2021-10-10 05:59 UTC, Haozeee commented on src/main/java/seedu/plannermd/commons/core/Messages.java
> +    public static final String MESSAGE_INVALID_PATIENT_DISPLAYED_INDEX = "The index provided is invalid";
I'll add one for Doctors as well. Refer to #62

2021-10-10 09:10 UTC, hpkoh requested changes

2021-10-10 09:10 UTC, hpkoh commented on src/main/java/seedu/plannermd/logic/commands/tagcommand/DeleteDoctorTagCommand.java
> +            throw new CommandException(MESSAGE_INVALID_PATIENT_DISPLAYED_INDEX);
I think this should be MESSAGE_INVALID_PATIENT_DISPLAYED_INDEX too right?

2021-10-10 09:23 UTC, merged