Create Appointment class
AY2122S1-CS2103T-T11-3/tp pull request #95
Opened 2021-10-13 18:08 UTC by pualixue

The `Appointment` class contains `Patient`, `Doctor`, `AppointmentDate`, `Session` and `Remark`.

`AppointmentDate` class represents a date and provides methods to check if a given date is valid.

`Session` class encapsulates the start and end time of an appointment.
The constructor takes in a starting time and a `Duration` to support commands like `start/20/10/2021 15:00 time/30`. The parser should pass `"15:00"` and `Duration(30)` to the constructor. The end time is calculated automatically in the `Session` class.
This class also provides a method to check if two sessions clash with each other. This method will then be used by the `Appointment` class to detect clashes with other existing appointments. New appointments that clash with existing ones should not be allowed to be added.

2021-10-14 03:10 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +            .withResolverStyle(ResolverStyle.SMART);
Perhaps the date and time formatter can be combined together so that when the user enters a start date, he can just enter the date and time together using something like `start/20/10/2021 18:00` instead of having to enter the fields separately.
```java
DateTimeFormatter.ofPattern("d/M/yyyy H:M")
```

2021-10-14 03:10 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/Appointment.java
> +    private final AppointmentDateTime endDateTime;
I think we mentioned last Sunday that an appointment should not have an end time, just a start time.

2021-10-14 03:15 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +            + "1. Must be a valid date (after now)\n"
Should we not allow users to enter appointments with a start date before now? I think there could be times when a clinic receptionist might want to enter an old appointment. For instance, a clinic receptionist may have forgotten to add a previous appointment and would want to add it now for record-keeping purposes. What do the rest think?

2021-10-14 03:17 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +    public final LocalTime time;
Since an `AppointmentDateTime` has a non-null date and time field, perhaps the date and time can be stored together in a `LocalDateTime` object rather than storing them seperately.

2021-10-14 04:41 UTC, pualixue commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +            .withResolverStyle(ResolverStyle.SMART);
Good idea

2021-10-14 05:33 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/Appointment.java
> +    private final AppointmentDateTime endDateTime;
I was thinking that we detect an appointment as clashing if it starts within 5 mins of another appointment since in most clinics an appointment will usually take less than 5 mins.

2021-10-14 07:07 UTC, pualixue commented on src/main/java/seedu/plannermd/model/appointment/Appointment.java
> +    private final AppointmentDateTime endDateTime;
I see, this works too but sometimes a patient or doctor might want a longer appointment?

2021-10-14 09:06 UTC, hpkoh commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +        boolean isSecondEndDateBetweenFirstAppt = isDateBetween(secondEndDate, firstStartDate, firstEndDate);
If im not wrong the first two lines suffices to check for the clash right. In line 127, if the `secondStartDate` falls between the `firstStartDate` and `firstEndDate`, the `firstStartDate` would necessarily be between the `secondStartDate` and `secondStartDate`. That would be checked in line 126. Similar for line 128.

However I think we can fix the date to entirely do away with this check

2021-10-14 09:07 UTC, hpkoh commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDateTime.java
> +        boolean isSecondEndTimeBetweenFirstAppt = isTimeBetween(secondEndTime, firstStartTime, firstEndTime);
similar to my above comment

2021-10-15 01:32 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/model/appointment/Duration.java
> +    public static final String MESSAGE_CONSTRAINTS = "The duration should be an integer between 1-60 minutes.";
should we set an upper limit to the duration of an appointment?

2021-10-15 01:32 UTC, ChuangZheQuan commented on src/main/java/seedu/plannermd/model/appointment/Appointment.java
> +
I don't think an upper limit is necessary, to give the clinic as much flexibility as possible. For example, some clinics may want to do an x-ray or blood test and all this require time. It will be a little redundant if the receptionist have to create more consecutive appointments just to extend the length of a session

2021-10-15 04:37 UTC, jiayi1129 requested changes
Looks good! Could you perhaps add the corresponding test cases for these classes created as well?

2021-10-15 05:51 UTC, hpkoh approved these changes
LGTM 👍

2021-10-15 12:18 UTC, Haozeee commented on src/main/java/seedu/plannermd/model/appointment/AppointmentDate.java
> +    public static boolean isValidAppointmentDate(String test) {
Since you have a `isValidAppointmentDate` and `isValidDuration` method, perhaps can also insert a `isValidAppointment` method here. I think it will be useful when adding or editing appointments.

2021-10-16 03:13 UTC, merged